# Generated by Django 4.2.2 on 2023-07-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0002_rename_author_user_id_contributors_author_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='author_user',
            new_name='user',
        ),
    ]
