# Generated by Django 5.0.1 on 2024-04-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_issues_assignee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('0', 'À Faire'), ('1', 'En Cours'), ('2', 'Terminé')], default='0', max_length=1),
        ),
    ]
