# Generated by Django 5.0.1 on 2024-04-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_issues_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
